services:
  - type: web
    name: online-video-downloader
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: YTDL_NO_UPDATE
        value: "1"
      - key: WEB_CONCURRENCY
        value: 2
    healthCheckPath: /health
    autoDeploy: true
